version: "3.4"
services:
  mongo:
    image: mongo:4.4.4-bionic
    command: ["--replSet", "rs0", "--bind_ip_all"]
    hostname: mongo
    healthcheck:
      test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1
      interval: 10s
      start_period: 30s
    restart: always